// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwhaaoqlcgekxchzqmbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3aGFhb3FsY2dla3hjaHpxbWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0OTUwNTUsImV4cCI6MjA4NjA3MTA1NX0.c87YlgTPJRn9cdvi8W6Y0KME0WBF5jbKB6L_hbPiL7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});